import turtle,time
alex = turtle.Turtle()
a = turtle.Screen()
a.title('abc')
a.bgcolor('yellow')
alex.color('red')
alex.shape('turtle')
alex.forward(100)
time.sleep(1)
alex.left(144)
alex.forward(100)
time.sleep(1)
alex.left(144)
alex.forward(100)
time.sleep(1)
alex.left(144)
alex.forward(100)
time.sleep(1)
alex.left(144)
alex.forward(100)